apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
       - name: cont1 
         resources:
           requests:
             memory: "64Mi"
             cpu: "50m"
           limits:
             memory: "256Mi"
             cpu: "100m"
