apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
       - image: lerndevops/springboot-mongo-app:latest
         name: cont1
         envFrom: 
          - configMapRef: 
              name: myapp-config
