resources:
 - deployment.yml
 - service.yml 
 - configmap.yml
patchesStrategicMerge:
 - patches/replica_count.yaml
 - patches/resource_limits.yaml
 - patches/env.yaml
#configMapGenerator:
#images:
#namespace: test
