kind: Service
apiVersion: v1
metadata:
  name: pyapp-svc
  namespace: default
spec: 
  type: NodePort
  selector: 
    app: pyapp
  ports:
    - port: 80 
      targetPort: 3000
      ##nodePort: 31311
